#!/usr/bin/env bash
# World wide web
printIt (){

    if [ "$2" ]
    then
        variable=$2
        dig "$2.""$1" | grep -A1 'ANSWER SECTION:' | tail -1 |
        awk -v var="$variable" '{print "The subdomain " var " is a " $4 " record and points to " $5}';
    elif [ "$1" ]
    then
        dig "www.""$1" | grep -A1 'ANSWER SECTION:' | tail -1 |
        awk '{ print "The subdomain www is a " $4 " record and points to " $5}';

        dig "lb-01.""$1" | grep -A1 'ANSWER SECTION:' | tail -1 |
        awk '{ print "The subdomain lb-01 is a " $4 " record and points to " $5}';

        dig "web-01.""$1" | grep -A1 'ANSWER SECTION:' | tail -1 |
        awk '{ print "The subdomain web-01 is a " $4 " record and points to " $5}';

        dig "web-02.""$1" | grep -A1 'ANSWER SECTION:' | tail -1 |
        awk '{ print "The subdomain web-02 is a " $4 " record and points to " $5}';
    fi
}
printIt "$1" "$2"
