#!/usr/bin/env bash
#!/usr/bin/env bash
# Install nginx
sudo apt-get update;
sudo apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP';
echo "Holberton School" | sudo tee "/var/www/html/index.nginx-debian.html";
sudo service nginx restart;
