#!/usr/bin/env bash
# Configure and install Haproxy
sudo apt-get update;
sudo apt-get -y install haproxy=1.6.\*;
new_redirect="
frontend firstbalance\n\t
    bind *:80\n\t
    mode http\n\t
    option forwardfor\n\t
    default_backend webservers\n\n
backend webservers\n\t
    balance 1616
"
echo -e "$new_redirect" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
