#!/usr/bin/env bash
# Install haproxy and add load balancer
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*
new_redirect="frontend firstbalance\n\tbind *:80\n\tmode http\n\tdefault_backend we\
bservers\n\nbackend webservers\n\tbalance roundrobin\n\tserver 1673-web-01 3.80.122\
.135:80 check\n\tserver 1673-web-02 35.227.101.25:80 check\n"
echo -e "$new_redirect" | sudo tee "/etc/haproxy/haproxy.cfg"
sudo service haproxy restart


# #!/usr/bin/env bash
# # Configure and install Haproxy
# sudo apt-get update;
# sudo apt-get -y install haproxy=1.6.\*;
# new_redirect="
# frontend firstbalance\n\t
#     bind *:80\n\t
#     mode http\n\t
#     option forwardfor\n\t
#     default_backend webservers\n\n
# backend webservers\n\t
#     balance 1616
# "
# echo -e "$new_redirect" >> /etc/haproxy/haproxy.cfg
# sudo service haproxy restart
