#!/usr/bin/env bash
# change user of nginx
sudo sed -i 's/www-data/nginx/' /etc/nginx/nginx.conf
sed -ie '21s/80/8080/' /etc/nginx/sites-enabled/default
sed -ie '22s/80/8080/' /etc/nginx/sites-enabled/default
sudo su nginx -c sudo service nginx restart;
