#!/usr/bin/env bash
# change user of nginx
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo chown nginx:nginx /etc/nginx
chmod 700 nginx.conf
pkill apache2
sudo -u nginx service nginx restart
